[tool.poetry]
name = "utils"
version = "0.1.0"
description = "Random utils"
authors = ["Martin ErrÃ¡zquin"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
